// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzlobPd8637Ec42L70wFHXpZE8g1bq_I',
    appId: '1:925477457595:android:0f8767de1f06f87816a39e',
    messagingSenderId: '925477457595',
    projectId: 'laminitis-app',
    storageBucket: 'laminitis-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mv2O8uhy-67G3OoO5jMzM0cnCkpM-fI',
    appId: '1:925477457595:ios:2e636979368a89f016a39e',
    messagingSenderId: '925477457595',
    projectId: 'laminitis-app',
    storageBucket: 'laminitis-app.appspot.com',
    androidClientId: '925477457595-jl9dfk9ib59utgbcgiq48iknibo02r86.apps.googleusercontent.com',
    iosClientId: '925477457595-o6c4ulb3erhntiu6p9eu4nokc5b5bmsu.apps.googleusercontent.com',
    iosBundleId: 'com.lami-tag.lamimvp',
  );

}